package jaso.lm;

public enum LockStatus {
    NEW,
    WAITING,
    GRANTED_SHARED,
    GRANTED_EXCLUSIVE,
    
    WOULD_DEADLOCK,
    
    PROMOTING,
    DEMOTING,
       
    NOT_SHARED, NOT_EXCLUSIVE,
    
    UNKNOWN_TRANSACTION, DUPLICATE_LOCK, LOCK_DOES_NOT_EXIST, TRANSACTION_ABORTED, TRANSACTION_COMMITTED,
}
